@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU1NTkzMDc0LCJleHAiOjE3NTYxMTE0NzR9.YFVgUB1k1QygBuSxmZ7FJ4kwQKpheZsAvJA01uoLcuI
@BASE_URL = http://localhost:3002/api/cart


### Add new item to cart
POST {{BASE_URL}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "productId": 9,
  "qty": 15
}


### Update cart Item
PATCH {{BASE_URL}}/4
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "qty": 50
}


### Delete cart Item
DELETE {{BASE_URL}}/11
Content-Type: application/json
Authorization: Bearer {{TOKEN}}


### Get cart
GET {{BASE_URL}}/cart
Authorization: Bearer {{TOKEN}}