@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU1MzQwMTgzLCJleHAiOjE3NTU4NTg1ODN9.SCztqgCtJ7CmD69PhAydxrGKmnj6sPeUtJSeBohiQrQ


### Add new item to cart
POST http://localhost:9003/api/cart
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": 9,
  "qty": 15
}


### Update cart Item
PATCH http://localhost:9003/api/cart/6
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "qty": 105
}


### Delete cart Item
DELETE http://localhost:9003/api/cart/1
Content-Type: application/json
Authorization: Bearer {{token}}


### Get cart
GET http://localhost:9003/api/cart
Authorization: Bearer {{token}}



# --------------------------------------------------------------


### Create Order
POST http://localhost:9003/api/orders
Content-Type: application/json

{
  "name": "New Product",
  "description": "This is a new product",
  "price": 29,
  "stock": 100
}


### Delete Order
DELETE http://localhost:9003/api/orders/1
Content-Type: application/json


### Get Orders
GET http://localhost:9003/api/orders


### Get Order by ID
GET http://localhost:9003/api/orders/1