@TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU1NTkzMDc0LCJleHAiOjE3NTYxMTE0NzR9.YFVgUB1k1QygBuSxmZ7FJ4kwQKpheZsAvJA01uoLcuI
@BASE_URL = http://localhost:3001/api/user


### Register user
POST {{BASE_URL}}/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john@example.com",
  "password": "StrongPass123!"
}


### Login user
POST {{BASE_URL}}/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "StrongPass123!"
}


### Validate token
GET {{BASE_URL}}/validate
Authorization: Bearer {{TOKEN}}