@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2huQGV4YW1wbGUuY29tIiwiaWF0IjoxNzU1MzQwMTgzLCJleHAiOjE3NTU4NTg1ODN9.SCztqgCtJ7CmD69PhAydxrGKmnj6sPeUtJSeBohiQrQ


### Register user
POST http://localhost:3001/api/user/register
Content-Type: application/json

{
  "username": "john_doe",
  "email": "john@example.com",
  "password": "StrongPass123!"
}


### Login user
POST http://localhost:3001/api/user/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "StrongPass123!"
}


### Validate token
GET http://localhost:3001/api/user/validate
Authorization: Bearer {{token}}